set guioptions=Acedi
set lines=30
set columns=132
set guifont=Iosevka\ Term\ SS07\ Semibold\ 11
set stal=2
set guicursor=n-v-c:ver25-Cursor/lCursor
set guicursor+=o:ver25-Cursor/lCursor
set guicursor+=sm:block-Cursor
set guicursor+=r-cr:hor20-Cursor/lCursor
" vim:fdm=marker
