#!/usr/bin/zsh
# This hook is sourced after every virtualenv is activated.

PS1="$_OLD_VIRTUAL_PS1"
_OLD_RPROMPT="$RPROMPT"
RPROMPT="[%{$fg_bold[green]%}env: %{$reset_color%}`basename \"$VIRTUAL_ENV\"`]$RPROMPT"
