#!/usr/bin/zsh
# This hook is sourced after every virtualenv is activated.

PS1="$_OLD_VIRTUAL_PS1"
_OLD_PROMPT="$PROMPT"
PROMPT="$PROMPT%{$reset_color%}· %{$fg_bold[cyan]%}`basename \"$VIRTUAL_ENV\"`%{$reset_color%} "
