# THIS FILE IS GENERATED BY antigen-hs!!!!

source /home/tama/Documents/DOTFILES/zsh/plugins/colors/zsh-syntax-highlighting.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/key-bindings/key-bindings.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/extract/extract.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/emoji/emoji.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/completion/completion.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/compfix/compfix.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/misc/misc.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/history/history.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/directories/directories.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/grep/grep.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/git/git.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/theme/theme.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/terminal/terminal.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/bureau/bureau.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/custom/custom.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/colored-man-pages/colored-man-pages.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/history-substring-search/history-substring-search.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/spectrum/spectrum.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/per-directory-history/per-directory-history.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/cp/cp.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/copyfile/copyfile.plugin.zsh
source /home/tama/Documents/DOTFILES/zsh/plugins/catimg/catimg.plugin.zsh
fpath+=/home/tama/.zsh/plugins/colors
fpath+=/home/tama/.zsh/plugins/key-bindings
fpath+=/home/tama/.zsh/plugins/extract
fpath+=/home/tama/.zsh/plugins/emoji
fpath+=/home/tama/.zsh/plugins/completion
fpath+=/home/tama/.zsh/plugins/compfix
fpath+=/home/tama/.zsh/plugins/misc
fpath+=/home/tama/.zsh/plugins/history
fpath+=/home/tama/.zsh/plugins/directories
fpath+=/home/tama/.zsh/plugins/grep
fpath+=/home/tama/.zsh/plugins/git
fpath+=/home/tama/.zsh/plugins/theme
fpath+=/home/tama/.zsh/plugins/terminal
fpath+=/home/tama/.zsh/plugins/bureau
fpath+=/home/tama/.zsh/plugins/custom
fpath+=/home/tama/.zsh/plugins/colored-man-pages
fpath+=/home/tama/.zsh/plugins/history-substring-search
fpath+=/home/tama/.zsh/plugins/fancy-ctrl-z
fpath+=/home/tama/.zsh/plugins/spectrum
fpath+=/home/tama/.zsh/plugins/per-directory-history
fpath+=/home/tama/.zsh/plugins/cp
fpath+=/home/tama/.zsh/plugins/copyfile
fpath+=/home/tama/.zsh/plugins/catimg
