# THIS FILE IS GENERATED BY antigen-hs!!!!

source /home/ramot/Documents/DOTFILES/zsh/plugins/key-bindings/key-bindings.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/setopts/setopts.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/completion/completion.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/history/history.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/directories/directories.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/dircycle/dircycle.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/extract/extract.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/grep/grep.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/nvm/nvm.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/rvm/rvm.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/terminal/terminal.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/autopair/autopair.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/colors/zsh-syntax-highlighting.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/history-substring-search/history-substring-search.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/async/async.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/arc/arc.plugin.zsh
source /home/ramot/Documents/DOTFILES/zsh/plugins/custom/custom.plugin.zsh
fpath+=/home/ramot/.zsh/plugins/key-bindings
fpath+=/home/ramot/.zsh/plugins/setopts
fpath+=/home/ramot/.zsh/plugins/completion
fpath+=/home/ramot/.zsh/plugins/zsh-completions
fpath+=/home/ramot/.zsh/plugins/history
fpath+=/home/ramot/.zsh/plugins/directories
fpath+=/home/ramot/.zsh/plugins/fancy-ctrl-z
fpath+=/home/ramot/.zsh/plugins/dircycle
fpath+=/home/ramot/.zsh/plugins/extract
fpath+=/home/ramot/.zsh/plugins/grep
fpath+=/home/ramot/.zsh/plugins/nvm
fpath+=/home/ramot/.zsh/plugins/virtualenvwrapper
fpath+=/home/ramot/.zsh/plugins/rvm
fpath+=/home/ramot/.zsh/plugins/terminal
fpath+=/home/ramot/.zsh/plugins/autopair
fpath+=/home/ramot/.zsh/plugins/colors
fpath+=/home/ramot/.zsh/plugins/history-substring-search
fpath+=/home/ramot/.zsh/plugins/zsh-autosuggestions
fpath+=/home/ramot/.zsh/plugins/async
fpath+=/home/ramot/.zsh/plugins/arc
fpath+=/home/ramot/.zsh/plugins/custom
